name: Compile LibVLC 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false

      - name: Set environment
        run: |
          echo "ANDROID_SDK=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          git config --global user.email "noreply@example.com"
          git config --global user.name "Your Name"
          rm -rf vlc-android

      - name: Clone vlc-android
        run: git clone https://code.videolan.org/videolan/vlc-android.git
        
      - name: Clone libvlc
        working-directory: vlc-android
        run: buildsystem/compile.sh --init
        
      - name: Run compile (arm)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -a arm
        
      - name: Run compile (arm64)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -a arm64
        
      - name: Run compile (x86)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -a x86
        
      - name: Run compile (x86_64)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -a x86_64
      
      - name: Archive aar
        uses: actions/upload-artifact@v3
        with:
          name: LibVLCJNI
          path: vlc-android/libvlcjni/libvlc/build/outputs
